"""Domain guard for banking-related questions."""

BANKING_KEYWORDS = {
    "account",
    "atm",
    "bank",
    "banking",
    "basel",
    "bond",
    "capital",
    "cbdc",
    "central bank",
    "cheque",
    "check",
    "cibil",
    "collateral",
    "core banking",
    "credit",
    "credit score",
    "crr",
    "currency",
    "debit",
    "demat",
    "deposit",
    "digital rupee",
    "emi",
    "equity",
    "fd",
    "fdic",
    "fdi",
    "finance",
    "financial",
    "fintech",
    "forex",
    "hypothecation",
    "imps",
    "inflation",
    "insurance",
    "interest",
    "investment",
    "kyc",
    "lien",
    "liquidity",
    "loan",
    "microfinance",
    "monetary",
    "mortgage",
    "mutual fund",
    "nbfc",
    "neft",
    "npa",
    "nri",
    "open banking",
    "overdraft",
    "payment",
    "pledge",
    "rate",
    "rbi",
    "rd",
    "repo",
    "repo rate",
    "reverse repo",
    "rtgs",
    "savings",
    "securitization",
    "slr",
    "stock",
    "swift",
    "transaction",
    "transfer",
    "upi",
    "withdraw",
}


def is_banking_related(question: str) -> bool:
    """Return True when a question appears to be banking or finance related."""
    question_lower = question.lower()
    return any(keyword in question_lower for keyword in BANKING_KEYWORDS)
